all:
  children:
    jenkins_master:
      hosts:
        master:
          ansible_host: <master_ip>
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    jenkins_slave:
      hosts:
        slave:
          ansible_host: <slave_ip>
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519

